export enum MutationTypes {
  ADD_SPAWN = 'ADD_SPAWN',
  INSERT_SPAWNS = 'INSERT_SPAWNS',
  UPDATE_COORDS = 'UPDATE_COORDS',
  UPDATE_SPAWN_COOLDOWN = 'UPDATE_SPAWN_COOLDOWN',
  SET_CURRENT_MOB = 'SET_CURRENT_MOB'
}
